In [5]:
import math

print(math.comb(12, 3))  # 220

220


In [6]:
print(math.factorial(5))  # 120

120


In [7]:
print(math.gcd(120, 210, 360))  # 30

30


In [8]:
print(math.lcm(10, 20, 30, 40))  # 120

120


In [9]:
print(math.perm(4, 2))  # 12
print(math.perm(4))  # 24

12
24


In [10]:
print(math.prod(range(10, 21)))  # 6704425728000

6704425728000


In [11]:
print(math.exp(3.5))  # 33.11545195869231

33.11545195869231


In [12]:
print(math.log(10))     # 2.302585092994046
print(math.log(10, 2))  # 3.3219280948873626

2.302585092994046
3.3219280948873626


In [13]:
print(math.pow(2, 10))     # 1024.0
print(math.pow(4.5, 3.7))  # 261.1477575641718

1024.0
261.1477575641718


In [14]:
print(math.dist((0, 0, 0), (1, 1, 1)))  # 1.7320508075688772

1.7320508075688772


In [15]:
print(math.hypot(1, 1, 1))  # 1.7320508075688772
print(math.hypot(3, 4))     # 5.0

1.7320508075688772
5.0


In [16]:
print(round(math.degrees(math.asin(0.5)), 1))  # 30.0
print(round(math.sin(math.radians(30)), 1))   # 0.5

30.0
0.5


In [17]:
print(math.gamma(3))    # 2.0
print(math.gamma(3.5))  # 3.323350970447842
print(math.gamma(4))    # 6.0

2.0
3.323350970447842
6.0


In [18]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"a[0] = {a[0]}")
print(f"b[0] = {b[0]}")

# Вывод программы

# a[0] = 1

# b[0] = [1 2]

a[0] = 1
b[0] = [1 2]


In [19]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}, a.size = {a.size}, a.dtype = {a.dtype}")

# Вывод программы

# a.ndim = 2, a.shape = (4, 2), a.size = 8, a.dtype = int32

a.ndim = 2, a.shape = (4, 2), a.size = 8, a.dtype = int64


In [20]:
import numpy as np

a = np.array([1, 2, 3], dtype="uint8")
a[0] = 256
print(a)

# Вывод программы

# [0 2 3]

OverflowError: Python integer 256 out of bounds for uint8

In [21]:
import numpy as np

a = np.array([1, 2.5, 3])
print(a)
print(a.dtype)

b = np.array(['text', 1, 2.5])
print(b)
print(b.dtype)

# Вывод программы

# [1.  2.5 3. ]

# float64

# ['text' '1' '2.5']

# <U32

[1.  2.5 3. ]
float64
['text' '1' '2.5']
<U32


In [22]:
import numpy as np

a = np.zeros((4, 3))
print(a)
print()
a = np.zeros((4, 3), dtype="int32")
print(a)

# Вывод программы

# [[0. 0. 0.]

# [0. 0. 0.]

# [0. 0. 0.]

# [0. 0. 0.]]

#

# [[0 0 0]

# [0 0 0]

# [0 0 0]

# [0 0 0]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
import numpy as np

a = np.ones((4, 3))
print(a)

# Вывод

# [[1. 1. 1.]

# [1. 1. 1.]

# [1. 1. 1.]

# [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
import numpy as np

a = np.eye(5, 5, dtype="int8")
print(a)

# Вывод

# [[1 0 0 0 0]

# [0 1 0 0 0]

# [0 0 1 0 0]

# [0 0 0 1 0]

# [0 0 0 0 1]]


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [25]:
import numpy as np

a = np.arange(1, 10)
print(a)
print()
a = np.arange(1, 5, 0.4)
print(a)

# Вывод

# [1 2 3 4 5 6 7 8 9]

#

# [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


[1 2 3 4 5 6 7 8 9]

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [27]:
import numpy as np

a = np.linspace(1, 5, 10)
print(a)

# Вывод

#[1. 1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
# 3.66666667 4.11111111 4.55555556 5.]

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [28]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 6))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [29]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a.resize((2, 2, 3))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [30]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 3, -1))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [31]:
import numpy as np

a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[10 10 10]
[8 6 4]
[ 9 16 21]
[9.         4.         2.33333333]


In [32]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
print(a @ b)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [33]:
import numpy as np

a = np.arange(1, 13).reshape(4, 3)
print(a)
print("Транспонирование")
print(a.transpose())
print("Поворот влево")
print(np.rot90(a))
print("Поворот вправо")
print(np.rot90(a, -1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Транспонирование
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Поворот влево
[[ 3  6  9 12]
 [ 2  5  8 11]
 [ 1  4  7 10]]
Поворот вправо
[[10  7  4  1]
 [11  8  5  2]
 [12  9  6  3]]


In [34]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum())
print(a.min())
print(a.max())

45
1
9


In [35]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum(axis=0))  # Сумма по столбцам
print(a.sum(axis=1))  # Сумма по строкам
print(a.min(axis=0))  # Минимум по столбцам
print(a.max(axis=1))  # Максимум по строкам

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


In [36]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print(a[:2, 2:])     # Срез: 2 строки, последние 2 столбца
print()
print(a[:, ::2])     # Срез всех строк, каждый второй столбец

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[3 4]
 [7 8]]

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [38]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)
for row in a:
    print(row)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [39]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print("; ".join(str(el) for el in a.flat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12


In [40]:
import numpy as np
from time import time

t = time()
print(f"Результат итератора: {sum(x **0.5 for x in range(10** 7))}.")
print(f"{time() - t} с.")
t = time()
print(f"Результат numpy: {np.sqrt(np.arange(10 ** 7)).sum()}.")
print(f"{time() - t} с.")

Результат итератора: 21081849486.442493.
1.6693320274353027 с.
Результат numpy: 21081849486.442448.
0.09058642387390137 с.
